services:
  poste:
    image: analogic/poste.io
    container_name: poste
    restart: always
    ports:
      - "25:25"      # SMTP
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "110:110"    # POP3
      - "143:143"    # IMAP
      - "993:993"    # IMAPS
      - "995:995"    # POP3S
      - "4190:4190"  # Sieve
    volumes:
      - ./mail:/data
    environment:
      - "HTTPS=ON"   # Habilitar HTTPS
      - "SIEVE=ON"   # Habilitar Sieve
  
  fedora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-fedora
    stdin_open: true
    tty: true
    volumes:
      - ./datos:/home/miusuario/datos
    networks:
      - fedora_net
    restart: unless-stopped
    command: /bin/bash

networks:
  fedora_net:
    driver: bridge